apiVersion: config.openshift.io/v1
kind: OAuth
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: developer
    type: HTPasswd
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    accessTokenInactivityTimeoutSeconds: 900
