apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: developer
    type: HTPasswd
  tokenConfig:
    accessTokenInactivityTimeoutSeconds: 907
    accessTokenMaxAgeSeconds: 76400
